# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9fd18808-66a0-4bf8-85ba-3c74eed22a34";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9fd18808-66a0-4bf8-85ba-3c74eed22a34".device = "/dev/disk/by-uuid/9fd18808-66a0-4bf8-85ba-3c74eed22a34";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/20B6-C559";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-6b985d7e-f11a-4a4f-a606-f28b6a565c2e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
